import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import type { Country } from '../src/types/country.ts'
import { normalizeCountryFile } from '../src/data/countries/normalization.ts'

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url))
const PROJECT_ROOT = path.resolve(SCRIPT_DIR, '..')

const DEFAULT_FACTBOOK_ROOT = '/home/matheus/code/factbook.json'
const FACTBOOK_ROOT = path.resolve(
  process.env.FACTBOOK_PATH ?? DEFAULT_FACTBOOK_ROOT,
)
const EXCLUDED_REGION_DIRS = new Set(['world', 'meta', 'oceans'])

const COUNTRIES_OUTPUT = path.join(
  PROJECT_ROOT,
  'src',
  'data',
  'countries',
  'countries.json',
)
const EXCLUDED_OUTPUT = path.join(
  PROJECT_ROOT,
  'src',
  'data',
  'countries',
  'EXCLUDED.md',
)

interface ExclusionRecord {
  readonly source: string
  readonly problems: readonly string[]
}

export function generateCountries(factbookRoot: string = FACTBOOK_ROOT): {
  countries: Country[]
  exclusions: ExclusionRecord[]
} {
  if (!existsSync(factbookRoot)) {
    throw new Error(`FactsBook root does not exist: ${factbookRoot}`)
  }

  const regionDirs = readdirSync(factbookRoot, { withFileTypes: true })
    .filter(
      (entry) => entry.isDirectory() && !EXCLUDED_REGION_DIRS.has(entry.name),
    )
    .map((entry) => entry.name)
    .sort()

  const countries: Country[] = []
  const exclusions: ExclusionRecord[] = []
  const seenIds = new Map<string, string>()

  for (const regionDir of regionDirs) {
    const regionPath = path.join(factbookRoot, regionDir)
    const files = readdirSync(regionPath)
      .filter((file) => file.endsWith('.json'))
      .sort()

    for (const file of files) {
      const id = file.slice(0, -'.json'.length)
      const source = path.join(regionDir, file)
      const existing = seenIds.get(id)
      if (existing !== undefined) {
        exclusions.push({
          source,
          problems: [`id: duplicate id "${id}" also produced by ${existing}`],
        })
        continue
      }
      seenIds.set(id, source)

      let document: unknown
      try {
        document = JSON.parse(readFileSync(path.join(regionPath, file), 'utf8'))
      } catch (error) {
        exclusions.push({
          source,
          problems: [`json: could not parse file: ${(error as Error).message}`],
        })
        continue
      }

      const result = normalizeCountryFile(id, document)
      if (result.country === undefined) {
        exclusions.push({ source, problems: [...result.problems] })
      } else {
        countries.push(result.country)
      }
    }
  }

  countries.sort((a, b) => a.id.localeCompare(b.id))
  exclusions.sort((a, b) => a.source.localeCompare(b.source))
  return { countries, exclusions }
}

function renderExcludedMarkdown(
  exclusions: readonly ExclusionRecord[],
  countriesCount: number,
): string {
  const lines: string[] = [
    '# Excluded FactsBook Records',
    '',
    'This file is generated by `npm run generate:countries`. It documents',
    'records that could not be normalized into canonical GeoStake country data,',
    'along with the required field(s) that were missing or invalid. Entries',
    'listed here are intentionally excluded from the canonical dataset.',
    '',
    `- Source: the locally cloned FactsBook repository`,
    `- Total records processed: ${countriesCount + exclusions.length}`,
    `- Valid GeoStake countries: ${countriesCount}`,
    `- Excluded records: ${exclusions.length}`,
    '',
    '## Exclusions',
    '',
    '| Source file | Problems |',
    '| --- | --- |',
  ]
  for (const exclusion of exclusions) {
    lines.push(`| ${exclusion.source} | ${exclusion.problems.join('; ')} |`)
  }
  lines.push('')
  return lines.join('\n')
}

function main(): void {
  const { countries, exclusions } = generateCountries()

  writeFileSync(
    COUNTRIES_OUTPUT,
    `${JSON.stringify(countries, null, 2)}\n`,
    'utf8',
  )
  writeFileSync(
    EXCLUDED_OUTPUT,
    renderExcludedMarkdown(exclusions, countries.length),
    'utf8',
  )

  console.log(`FactsBook source: ${FACTBOOK_ROOT}`)
  console.log(`Valid GeoStake countries: ${countries.length}`)
  console.log(`Excluded records: ${exclusions.length}`)
  console.log(`Wrote ${COUNTRIES_OUTPUT}`)
  console.log(`Wrote ${EXCLUDED_OUTPUT}`)
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  main()
}
